import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { normalizeShippoRates, requestShippoRates, toShippoParcel } from '../api/_lib/shippoRates.js';

test('Shippo parcel mapping uses authoritative calculator output', () => { assert.deepEqual(toShippoParcel({lengthIn:10,widthIn:8,heightIn:4,totalWeightOz:38}), {length:'10',width:'8',height:'4',distance_unit:'in',weight:'38',mass_unit:'oz'}); });
test('rates normalize, filter malformed entries, add handling, and sort cheapest first', () => { const rates = normalizeShippoRates([{object_id:'expensive',amount:'10.00',currency:'USD',provider:'UPS',servicelevel:{name:'Ground'}},{object_id:'cheap',amount:'4.25',currency:'usd',provider:'USPS',servicelevel:{name:'Ground Advantage'},estimated_days:4},{object_id:'bad',amount:'NaN',currency:'USD'},{object_id:'eur',amount:'1',currency:'EUR'},{amount:'2',currency:'USD'}],150); assert.deepEqual(rates.map((rate) => rate.id),['cheap','expensive']); assert.equal(rates[0].carrierAmountCents,425); assert.equal(rates[0].handlingFeeCents,150); assert.equal(rates[0].customerAmountCents,575); assert.equal(rates[0].estimatedDays,4); });
test('Shippo request uses shipment API addresses and parcel without buying a label', async () => { const previous = process.env.SHIPPO_API_TOKEN; process.env.SHIPPO_API_TOKEN='test'; let captured; const fetchImpl = async (url, options) => { captured={url,options,body:JSON.parse(options.body)}; return {ok:true,json:async()=>({rates:[]})}; }; await requestShippoRates({fromAddress:{country:'US'},toAddress:{country:'CA'},parcel:{lengthIn:8,widthIn:6,heightIn:2,totalWeightOz:9},fetchImpl}); if (previous == null) delete process.env.SHIPPO_API_TOKEN; else process.env.SHIPPO_API_TOKEN=previous; assert.equal(captured.url,'https://api.goshippo.com/shipments'); assert.deepEqual(captured.body.parcels,[{length:'8',width:'6',height:'2',distance_unit:'in',weight:'9',mass_unit:'oz'}]); assert.equal(captured.body.address_to.country,'CA'); assert.equal(captured.body.async,false); assert.doesNotMatch(captured.url,/transactions|labels/); });
test('rates endpoint is authenticated, owner-scoped, saved-address-only, and calculator-backed', async () => { const endpoint = await readFile(new URL('../api/shipping/rates.js',import.meta.url),'utf8'); assert.match(endpoint,/requireUser/); assert.match(endpoint,/userSnap\.data\(\)\?\.shippingAddress/); assert.match(endpoint,/loadOwnedShippingItems\(uid/); assert.match(endpoint,/calculateShipmentParcel/); assert.match(endpoint,/storedAddress\.validated !== true/); assert.doesNotMatch(endpoint,/req\.body\?\.(destination|parcel|packageId|shippingProfileId|amount)/); });
test('quote is server-owned, expires, and exposes only a reduced destination', async () => { const [endpoint,rules] = await Promise.all([readFile(new URL('../api/shipping/rates.js',import.meta.url),'utf8'),readFile(new URL('../firestore.rules',import.meta.url),'utf8')]); assert.match(endpoint,/15 \* 60_000/); assert.match(endpoint,/shippingRateQuotes/); assert.match(endpoint,/destination: \{ city:/); assert.match(rules,/shippingRateQuotes/); assert.match(rules,/allow read, write: if false/); });
test('free-only selections remain free while mixed selections use live rates', async () => { const endpoint = await readFile(new URL('../api/shipping/rates.js',import.meta.url),'utf8'); assert.match(endpoint,/items\.every\(isFree\)/); assert.match(endpoint,/customerAmountCents: 0/); assert.match(endpoint,/allFree \?/); });
test('shipping review selects only local quote state and does not charge or remove inventory', async () => { const profile = await readFile(new URL('../components/Profile.tsx',import.meta.url),'utf8'); const liveSection = profile.slice(profile.indexOf('Shipping method selected.')); assert.match(profile,/setSelectedRateId\(rate\.id\)/); assert.match(profile,/Calculating shipping options/); assert.match(profile,/Refresh rates/); assert.doesNotMatch(liveSection.slice(0,500),/handleCashShipping|handleConfirmShipping|shipItem|stripe/); });
test('origin and international destinations are not client controlled or US restricted', async () => { const endpoint = await readFile(new URL('../api/shipping/rates.js',import.meta.url),'utf8'); assert.match(endpoint,/SHIP_FROM_COUNTRY/); assert.match(endpoint,/toShippoAddress\(destination\)/); assert.doesNotMatch(endpoint,/countryCode\s*!==\s*['"]US/); assert.doesNotMatch(endpoint,/console\.log\(.*destination/); });
test('missing and rejected Shippo configuration returns actionable safe codes', async () => { const previous = process.env.SHIPPO_API_TOKEN; delete process.env.SHIPPO_API_TOKEN; await assert.rejects(requestShippoRates({fromAddress:{},toAddress:{},parcel:{}}),(error)=>error.error === 'SHIPPO_NOT_CONFIGURED'); process.env.SHIPPO_API_TOKEN='test'; const base={fromAddress:{},toAddress:{},parcel:{lengthIn:1,widthIn:1,heightIn:1,totalWeightOz:1}}; await assert.rejects(requestShippoRates({...base,fetchImpl:async()=>({ok:false,status:401,json:async()=>({})})}),(error)=>error.error === 'SHIPPO_AUTH_FAILED'); await assert.rejects(requestShippoRates({...base,fetchImpl:async()=>({ok:false,status:400,json:async()=>({detail:'invalid parcel'})})}),(error)=>error.error === 'SHIPPO_RATE_REQUEST_REJECTED'); if (previous == null) delete process.env.SHIPPO_API_TOKEN; else process.env.SHIPPO_API_TOKEN=previous; });
