import React from 'react';
import { Sparkles } from 'lucide-react';
import { MysteryBox } from '../../types';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { Surface } from '../ui/Surface';

export const HomeHero = ({ boxes, onExplore, onHowItWorks, onDepositOffer }: { boxes: MysteryBox[]; onExplore:()=>void; onHowItWorks:()=>void; onDepositOffer:()=>void }) => {
  const heroBoxes = boxes.filter((b) => b.image).slice(0, 3);
  return <section className="relative overflow-hidden bg-pullz-canvas px-3 pt-5 sm:px-6 lg:px-8"><div className="absolute left-1/2 top-0 h-72 w-72 -translate-x-1/2 rounded-full bg-pullz-primary/20 blur-3xl" aria-hidden="true"/><div className="relative mx-auto grid min-h-[460px] max-w-[1250px] items-center gap-8 rounded-pullz-xl border border-pullz-border-soft bg-pullz-background p-5 shadow-pullz-lg sm:p-8 lg:min-h-[540px] lg:grid-cols-[1fr_0.9fr] lg:p-10"><div><Badge variant="primary">THE ONLINE COLLECTIBLES PLATFORM</Badge><h1 className="mt-5 text-[42px] font-bold leading-[0.98] tracking-tight text-pullz-text sm:text-6xl lg:text-7xl">Pull Real Collectibles.</h1><p className="mt-5 max-w-xl text-base leading-7 text-pullz-text-secondary sm:text-lg">Open curated collectible cases featuring real trading cards. Keep your pulls, ship them to your door, or sell them back for site credit.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button onClick={onExplore}>Explore Cases</Button><Button variant="secondary" onClick={onHowItWorks}>How It Works</Button></div><p className="mt-5 text-sm font-medium text-pullz-text-muted">Real inventory · Visible odds · Tracked shipping</p><Surface variant="base" className="mt-6 max-w-md p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-pullz-sm bg-pullz-gold-soft text-pullz-gold"><Sparkles className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-pullz-text">First deposit bonus available</p><p className="text-xs text-pullz-text-muted">Preserved offer eligibility and top-up flow.</p></div><Button variant="ghost" className="px-3" onClick={onDepositOffer}>View</Button></div></Surface></div><div className="relative min-h-[280px] overflow-hidden rounded-pullz-xl border border-pullz-border-soft bg-pullz-surface p-5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_15%,rgba(36,107,253,0.18),transparent_45%)]"/><div className="relative grid h-full grid-cols-3 items-center gap-2">{heroBoxes.length ? heroBoxes.map((box, i)=><button key={box.id} type="button" onClick={onExplore} className={`group flex min-h-[230px] items-center justify-center rounded-pullz-lg border border-pullz-border-soft bg-pullz-card p-3 transition duration-220 hover:-translate-y-1 hover:border-pullz-primary/35 hover:shadow-pullz-md ${i===1?'translate-y-6':''}`}><img src={box.image} alt={`${box.name} collectible case`} className="max-h-52 w-full object-contain transition duration-200 group-hover:scale-105" loading={i===0?'eager':'lazy'} decoding="async"/></button>) : <div className="col-span-3 grid min-h-[260px] place-items-center text-center text-pullz-text-muted">Collectible cases load here.</div>}</div></div></div></section>;
};
