export type HomepageFaq = {
  id: string;
  question: string;
  answer: string;
  links?: Array<{ label: string; view: 'PROVABLY_FAIR' | 'SHIPPING_POLICY' | 'REFUND_POLICY' | 'TERMS' | 'CONTACT' }>;
};

// Used by both the homepage and the dedicated FAQ route so the public answers stay aligned.
export const HOMEPAGE_FAQS: HomepageFaq[] = [
  { id: 'what-is-pullz', question: 'What is Pullz.gg?', answer: 'Pullz.gg is an online collectibles platform. You choose a box, reveal a real collectible, and add it to your Pullz inventory. Depending on the item and available account options, you can keep it for shipping or exchange it for site credit.' },
  { id: 'are-items-real', question: 'Are the items real?', answer: 'Yes. Items displayed inside eligible boxes represent real physical products or collectibles. When you reveal an item, it is added to your account inventory so you can review the available keep, sell-back, and shipping options.' },
  { id: 'open-a-box', question: 'How do I open a box?', answer: 'Create or sign in to your account, choose a box, review its contents and odds, and select the open button. You can use coins for eligible openings, and some accounts or boxes may also have free, promotional, or reward openings. The revealed item is added to your inventory after the opening is completed.' },
  { id: 'view-odds', question: 'Can I see the odds before opening?', answer: 'Yes. Each box displays its available items and published odds before you open it. Pullz.gg also provides information explaining how box results are generated and verified.', links: [{ label: 'published odds', view: 'PROVABLY_FAIR' }, { label: 'generated and verified', view: 'PROVABLY_FAIR' }] },
  { id: 'after-reveal', question: 'What happens after I reveal an item?', answer: 'The item is added to your Pullz inventory. From there, you can review its details and choose from the actions currently available for that item, such as keeping it, selling it back for coins, or requesting shipment.' },
  { id: 'sell-back', question: 'How does selling an item back work?', answer: 'Eligible available items may include a sell-back option inside your inventory. Before confirming, the site shows the number of coins you will receive. Once a sell-back is completed, the item is no longer available for shipment.' },
  { id: 'request-shipping', question: 'How do I have an item shipped?', answer: 'Open your inventory, select one or more eligible available items, choose the shipping option, and provide or confirm your delivery address. Any applicable shipping charge, minimum requirement, or restriction is shown before the request is confirmed.', links: [{ label: 'shipping option', view: 'SHIPPING_POLICY' }] },
  { id: 'shipping-time', question: 'How long does shipping take?', answer: 'Processing and delivery times can vary based on item availability, destination, carrier service, and account review requirements. Tracking information is provided when the shipment is prepared where available.', links: [{ label: 'Processing and delivery times', view: 'SHIPPING_POLICY' }] },
  { id: 'multiple-items', question: 'Can I ship multiple items together?', answer: 'Yes. Eligible inventory items can be selected and submitted in the same shipment request. The shipment screen shows any applicable charges before confirmation.' },
  { id: 'coins', question: 'What are coins?', answer: 'Coins are the balance used for eligible box openings, shipping charges where enabled, and other supported features on Pullz.gg. Coin package pricing and any included bonus amount are shown before purchase or use.' },
  { id: 'bonus-coins', question: 'Do bonus or promotional coins expire?', answer: 'Coin packages can include bonus coins. The currently available package and promotional details are shown before purchase or use; review the offer details and terms that apply to a specific promotion.' },
  { id: 'daily-spin', question: 'What is the Daily Spin?', answer: 'The Daily Spin is an account feature that can award coins. Eligible signed-in users can spin once per 24-hour cooldown; available prize amounts and their configured odds are shown in the feature.' },
  { id: 'refunds', question: 'Can I get a refund for unused coins or opened boxes?', answer: 'Purchases, box openings, sell-backs, promotional balances, and refunds are governed by the Pullz.gg refund policy and terms of service. Review those policies before purchasing or opening a box, and contact support if you believe there was a billing or technical error.', links: [{ label: 'refund policy', view: 'REFUND_POLICY' }, { label: 'terms of service', view: 'TERMS' }] },
  { id: 'interrupted-opening', question: 'What happens if an opening is interrupted?', answer: 'Box results are recorded by the server as part of the completed opening transaction. If the page closes or the animation is interrupted, check your inventory and transaction history. Contact support if the result does not appear correctly.', links: [{ label: 'Contact support', view: 'CONTACT' }] },
  { id: 'fair-opening', question: 'How do I know an opening is fair?', answer: 'Pullz.gg publishes box odds and provides information about how results are generated and verified. Review the box details and the provably fair information before opening.', links: [{ label: 'provably fair information', view: 'PROVABLY_FAIR' }] },
  { id: 'eligibility', question: 'Who can use Pullz.gg?', answer: 'Users must be at least 18 years old and meet the location requirements stated in the Pullz.gg terms of service. Certain features, purchases, promotions, or shipping destinations may be restricted.', links: [{ label: 'terms of service', view: 'TERMS' }] },
  { id: 'shipping-destinations', question: 'Where can Pullz.gg ship?', answer: 'Available shipping destinations and restrictions are listed in the shipping policy. Some products or destinations may require additional processing, fees, or verification.', links: [{ label: 'shipping policy', view: 'SHIPPING_POLICY' }] },
  { id: 'contact-support', question: 'How can I contact support?', answer: 'Use the Pullz.gg support page and include the email address associated with your account, a description of the issue, and any relevant order, shipment, or transaction information. Do not include passwords or sensitive payment details.', links: [{ label: 'support page', view: 'CONTACT' }] }
];
