import React, { useMemo, useState } from 'react';
import { doc, updateDoc } from 'firebase/firestore';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import { db } from '../../firebase';
import { CaseItem, MysteryBox } from '../../types';
import { authedFetch } from '../../utils/authedFetch';

type Preview = { rows: any[]; boxPrice: number; currentSnapshot: any; proposedSnapshot: any; profitabilityWarning: boolean };
const money = (coins?: number | null) => coins == null ? '—' : `$${(Number(coins) / 100).toFixed(2)}`;
const date = (value: any) => value ? new Date(value?.seconds ? value.seconds * 1000 : value).toLocaleString() : 'Never';

export const BoxMarketPricingEditor = ({ box, items, onItemsChange }: { box: MysteryBox; items: CaseItem[]; onItemsChange: (items: CaseItem[]) => void }) => {
  const defaults = { enabled: false, provider: 'tcgdex' as const, marketplace: 'tcgplayer' as const, autoApplyEnabled: false, autoApplyThresholdPercent: 20 };
  const [config, setConfig] = useState({ ...defaults, ...(box.marketPricing || {}) });
  const [preview, setPreview] = useState<Preview | null>(null);
  const [busy, setBusy] = useState('');
  const [notice, setNotice] = useState('');
  const counts = useMemo(() => ({ automatic: items.filter((i) => i.pricingMode === 'automatic').length, manual: items.filter((i) => i.pricingMode !== 'automatic').length }), [items]);
  const patchItem = (id: string, patch: Partial<CaseItem>) => onItemsChange(items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const save = async () => { setBusy('save'); try { await updateDoc(doc(db, 'boxes', box.id), { marketPricing: config, items }); setNotice('Box pricing configuration saved.'); } finally { setBusy(''); } };
  const action = async (kind: 'preview' | 'apply' | 'sync') => { setBusy(kind); setNotice(''); try { await save(); const result: any = await authedFetch(`/api/admin/boxes/${box.id}/pricing/${kind}`, { method: 'POST', body: JSON.stringify(kind === 'apply' ? { approvedItemIds: preview?.rows.filter((r) => r.proposedValue > 0).map((r) => r.itemId) } : {}) }); if (result.preview) setPreview(result.preview); setNotice(kind === 'apply' ? `Applied ${result.updated || 0} price changes.` : kind === 'sync' ? `Safe sync applied ${result.updated || 0} changes.` : 'Preview is ready; no box values were changed.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Pricing request failed.'); } finally { setBusy(''); } };
  return <section className="mt-5 rounded-2xl border border-cyan-500/30 bg-[#0b0e14] p-3 sm:p-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h4 className="font-black text-white">Market Pricing</h4><p className="mt-1 text-xs text-amber-200"><AlertTriangle className="mr-1 inline h-4 w-4" />TCGdex values are reference prices for raw Pokémon cards only—not PSA, CGC, BGS, sealed, or guaranteed values.</p></div><button type="button" onClick={save} className="min-h-11 rounded-xl bg-white/10 px-4 text-sm font-bold text-white">Save pricing setup</button></div>
    <div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div>Automatic<br/><b className="text-white">{counts.automatic}</b></div><div>Manual<br/><b className="text-white">{counts.manual}</b></div><div>Missing pricing<br/><b className="text-white">{box.marketPricing?.itemsMissingPricing || 0}</b></div><div>Approval required<br/><b className="text-white">{box.marketPricing?.itemsPendingApproval || 0}</b></div><div>Box price<br/><b className="text-white">{money(box.price)}</b></div><div>Expected value<br/><b className="text-white">{money(box.pricingSnapshot?.expectedValue)}</b></div><div>Estimated margin<br/><b className="text-white">{box.pricingSnapshot ? `${box.pricingSnapshot.marginPercent.toFixed(1)}%` : '—'}</b></div><div>Last check / apply<br/><b className="text-white">{date(box.marketPricing?.lastCheckedAt)} / {date(box.marketPricing?.lastAppliedAt)}</b></div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs text-gray-400">Market pricing<select value={String(config.enabled)} onChange={(e) => setConfig((c) => ({ ...c, enabled: e.target.value === 'true' }))} className="mt-1 min-h-11 w-full rounded bg-[#131720] px-3 text-white"><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label className="text-xs text-gray-400">Automatic application<select value={String(config.autoApplyEnabled)} onChange={(e) => setConfig((c) => ({ ...c, autoApplyEnabled: e.target.value === 'true' }))} className="mt-1 min-h-11 w-full rounded bg-[#131720] px-3 text-white"><option value="false">Manual approval</option><option value="true">Safe automatic</option></select></label><label className="text-xs text-gray-400">Large-change threshold (%)<input type="number" min="1" max="100" value={config.autoApplyThresholdPercent} onChange={(e) => setConfig((c) => ({ ...c, autoApplyThresholdPercent: Math.min(100, Math.max(1, Number(e.target.value) || 20)) }))} className="mt-1 min-h-11 w-full rounded bg-[#131720] px-3 text-white" /></label></div>
    <div className="mt-5 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-white/10 p-3"><div className="flex items-center gap-3"><img src={item.image} className="h-10 w-10 rounded object-contain"/><div className="min-w-0"><b className="block truncate text-sm text-white">{item.name}</b><span className="text-xs text-gray-400">Current applied value {money(item.effectiveValue ?? item.price)} • {item.pricingStatus || 'manual'}</span></div></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><select aria-label={`${item.name} pricing mode`} value={item.pricingMode || 'manual'} onChange={(e) => patchItem(item.id, { pricingMode: e.target.value as any })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"><option value="manual">Manual</option><option value="automatic">Automatic TCGdex</option></select><input aria-label="TCGdex ID" placeholder="TCGdex ID" value={item.tcgdexId || ''} onChange={(e) => patchItem(item.id, { tcgdexId: e.target.value })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"/><input aria-label="Exact set" placeholder="Exact set" value={item.tcgdexSetId || ''} onChange={(e) => patchItem(item.id, { tcgdexSetId: e.target.value })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"/><input aria-label="Exact card number" placeholder="Card number" value={item.tcgdexCardNumber || ''} onChange={(e) => patchItem(item.id, { tcgdexCardNumber: e.target.value })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"/><input aria-label="Language" placeholder="Language" value={item.pricingLanguage || 'en'} onChange={(e) => patchItem(item.id, { pricingLanguage: e.target.value })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"/><select aria-label="Variant" value={item.pricingVariant || 'normal'} onChange={(e) => patchItem(item.id, { pricingVariant: e.target.value as any })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"><option value="normal">Normal</option><option value="reverse">Reverse holo</option><option value="holo">Holo</option></select><input aria-label="Manual value" type="number" min="0" placeholder="Manual coins" value={item.manualValue ?? ''} onChange={(e) => patchItem(item.id, { manualValue: Number(e.target.value), ...(item.pricingMode !== 'automatic' ? { effectiveValue: Number(e.target.value) } : {}) })} className="min-h-11 rounded bg-[#131720] px-2 text-xs text-white"/></div>{item.pricingError && <p className="mt-2 text-xs text-red-300">{item.pricingError}</p>}</article>)}</div>
    <div className="mt-4 grid gap-2 sm:grid-cols-3"><button type="button" disabled={!!busy} onClick={() => action('preview')} className="min-h-11 rounded-xl border border-cyan-400/40 text-sm font-bold text-cyan-100"><RefreshCw className={`mr-2 inline h-4 w-4 ${busy === 'preview' ? 'animate-spin' : ''}`}/>Preview Current Prices</button><button type="button" disabled={!preview || !!busy} onClick={() => action('apply')} className="min-h-11 rounded-xl bg-emerald-600 text-sm font-bold text-white">Apply Approved Prices</button><button type="button" disabled={!!busy} onClick={() => action('sync')} className="min-h-11 rounded-xl bg-blue-600 text-sm font-bold text-white">Sync All Eligible Prices</button></div>{notice && <p className="mt-3 text-sm text-gray-200">{notice}</p>}
    {preview && <div className="mt-5 overflow-x-auto"><div className="mb-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-5"><span>Box {money(preview.boxPrice)}</span><span>Current EV {money(preview.currentSnapshot.expectedValue)}</span><span>Proposed EV {money(preview.proposedSnapshot.expectedValue)}</span><span>Current margin {preview.currentSnapshot.marginPercent.toFixed(1)}%</span><span>Proposed margin {preview.proposedSnapshot.marginPercent.toFixed(1)}%</span></div>{preview.profitabilityWarning && <p className="mb-2 text-xs font-bold text-amber-300">Warning: proposed pricing falls outside this box’s profitability target.</p>}<table className="min-w-[720px] w-full text-left text-xs"><thead className="text-gray-500"><tr><th>Item</th><th>Current</th><th>Proposed</th><th>Change</th><th>Percent</th><th>Status</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.itemId} className="border-t border-white/10"><td className="py-2 text-white">{row.item}</td><td>{money(row.currentValue)}</td><td>{money(row.proposedValue)}</td><td>{money(row.dollarChange)}</td><td>{row.percentageChange == null ? '—' : `${row.percentageChange.toFixed(1)}%`}</td><td className={row.error ? 'text-amber-300' : 'text-emerald-300'}>{row.status}{row.error ? ` — ${row.error}` : ''}</td></tr>)}</tbody></table></div>}
  </section>;
};
