import React, { useEffect, useMemo, useState } from 'react';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { AlertTriangle, CheckCircle2, Plus, Save, Trash2 } from 'lucide-react';
import { db } from '../../firebase';
import { DEFAULT_SEO_SETTINGS, SeoSettings, normalizeSeoSettings, validateSeoSettings } from '../../utils/seoSettings';

const Card = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="rounded-xl border border-gray-800 bg-[#131720] p-4 sm:p-6"><h2 className="mb-4 text-lg font-bold text-white">{title}</h2>{children}</section>;
const Field = ({ label, value, onChange, multiline = false, hint, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; multiline?: boolean; hint?: string; type?: string; key?: React.Key }) => <label className="block"><span className="mb-1 block text-xs font-bold uppercase tracking-wide text-gray-500">{label}</span>{multiline ? <textarea value={value} onChange={e => onChange(e.target.value)} className="min-h-24 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 py-2 text-sm text-white" /> : <input type={type} value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 py-2 text-sm text-white" />}{hint && <span className="mt-1 block text-xs text-gray-500">{hint}</span>}</label>;
const Toggle = ({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) => <label className="flex cursor-pointer items-center justify-between gap-3 rounded-lg border border-gray-800 bg-[#0b0e14] p-3 text-sm text-gray-200"><span>{label}</span><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} className="h-4 w-4 accent-cyan-500" /></label>;

export const SeoManager = () => {
  const [settings, setSettings] = useState<SeoSettings>(DEFAULT_SEO_SETTINGS); const [saved, setSaved] = useState<SeoSettings>(DEFAULT_SEO_SETTINGS); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; getDoc(doc(db, 'site', 'seo')).then(s => { if (active) { const next = normalizeSeoSettings(s.data() as Partial<SeoSettings>); setSettings(next); setSaved(next); setLoading(false); } }).catch(() => { if (active) { setError('SEO settings could not be loaded. Defaults are shown.'); setLoading(false); } }); return () => { active = false; }; }, []);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (JSON.stringify(settings) !== JSON.stringify(saved)) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [settings, saved]);
  const dirty = JSON.stringify(settings) !== JSON.stringify(saved); const update = <K extends keyof SeoSettings>(key: K, value: SeoSettings[K]) => setSettings(prev => ({ ...prev, [key]: value }));
  const health = useMemo(() => { const checks = [['Title length', settings.seoTitle.length >= 50 && settings.seoTitle.length <= 60], ['Description length', settings.metaDescription.length >= 140 && settings.metaDescription.length <= 160], ['Canonical present', !!settings.canonicalUrl], ['Open Graph configured', !!(settings.openGraphTitle && (settings.openGraphImage || settings.fallbackOpenGraphImage))], ['Twitter configured', !!(settings.twitterTitle || settings.twitterImage || settings.fallbackTwitterImage)], ['Schema enabled', settings.enableOrganizationSchema || settings.enableWebsiteSchema], ['Favicon configured', !!settings.faviconUrl], ['Verification configured', !!(settings.googleVerification || settings.bingVerification || settings.pinterestVerification || settings.yandexVerification)], ['Robots configured', !!settings.robotsMeta]]; return { checks, score: Math.round(checks.filter(c => c[1]).length / checks.length * 100) }; }, [settings]);
  const save = async () => { const errors = validateSeoSettings(settings); if (errors.length && !window.confirm(`Please review these SEO warnings before saving:\n\n${errors.join('\n')}`)) return; try { await setDoc(doc(db, 'site', 'seo'), { ...settings, updatedAt: serverTimestamp() }, { merge: true }); setSaved(settings); setNotice('SEO settings saved successfully.'); } catch { setError('Unable to save SEO settings. Please try again.'); } };
  if (loading) return <div className="rounded-xl border border-gray-800 bg-[#131720] p-8 text-center text-gray-400">Loading SEO settings…</div>;
  const image = settings.openGraphImage || settings.fallbackOpenGraphImage || settings.homepageShareImage;
  return <div className="space-y-6 pb-8">{(notice || error) && <div className={`flex gap-2 rounded-lg border p-3 text-sm ${error ? 'border-red-500/40 bg-red-500/10 text-red-200' : 'border-emerald-500/40 bg-emerald-500/10 text-emerald-200'}`}>{error ? <AlertTriangle className="h-5 w-5" /> : <CheckCircle2 className="h-5 w-5" />}{error || notice}</div>}
    {dirty && <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">You have unsaved changes. Leaving this page will discard them.</div>}
    <Card title="SEO Health"><div className="mb-3 flex items-center gap-4"><strong className="text-3xl text-cyan-300">{health.score}/100</strong><span className="text-sm text-gray-400">Complete the failed checks below to improve this score.</span></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{health.checks.map(([label, ok]) => <div key={label as string} className={`rounded-lg p-2 text-sm ${ok ? 'bg-emerald-500/10 text-emerald-200' : 'bg-amber-500/10 text-amber-100'}`}>{ok ? '✔' : '•'} {label as string}</div>)}</div></Card>
    <Card title="General SEO"><div className="grid gap-4 md:grid-cols-2"><Field label="Site Name" value={settings.siteName} onChange={v => update('siteName', v)} /><Field label="SEO Title" value={settings.seoTitle} onChange={v => update('seoTitle', v)} hint={`${settings.seoTitle.length}/50–60 recommended characters`} /><div className="md:col-span-2"><Field label="Meta Description" value={settings.metaDescription} onChange={v => update('metaDescription', v)} multiline hint={`${settings.metaDescription.length}/140–160 recommended characters`} /></div><Field label="Canonical URL" value={settings.canonicalUrl} onChange={v => update('canonicalUrl', v)} type="url" /><div className="grid gap-2"><Toggle label="Enable Indexing" value={settings.indexPage} onChange={v => update('indexPage', v)} /><Toggle label="Enable Follow Links" value={settings.followLinks} onChange={v => update('followLinks', v)} /></div></div></Card>
    <Card title="Google Search Preview"><div className="rounded-lg bg-white p-4 font-sans"><p className="text-xl text-[#1a0dab]">{settings.seoTitle || settings.siteName}</p><p className="text-sm text-[#188038]">{settings.canonicalUrl}</p><p className="mt-1 text-sm text-[#4d5156]">{settings.metaDescription}</p></div></Card>
    <Card title="Social Sharing"><div className="grid gap-4 md:grid-cols-2"><Field label="Open Graph Title" value={settings.openGraphTitle} onChange={v => update('openGraphTitle', v)} /><Field label="Open Graph Image URL" value={settings.openGraphImage} onChange={v => update('openGraphImage', v)} type="url" /><div className="md:col-span-2"><Field label="Open Graph Description" value={settings.openGraphDescription} onChange={v => update('openGraphDescription', v)} multiline /></div><Field label="Twitter Title" value={settings.twitterTitle} onChange={v => update('twitterTitle', v)} /><Field label="Twitter Image URL" value={settings.twitterImage} onChange={v => update('twitterImage', v)} type="url" /><div className="md:col-span-2"><Field label="Twitter Description" value={settings.twitterDescription} onChange={v => update('twitterDescription', v)} multiline /></div><label className="text-xs font-bold uppercase text-gray-500">Twitter Card<select value={settings.twitterCard} onChange={e => update('twitterCard', e.target.value as SeoSettings['twitterCard'])} className="mt-1 block w-full rounded-lg border border-gray-700 bg-[#0b0e14] p-2 text-sm normal-case text-white"><option value="summary">summary</option><option value="summary_large_image">summary_large_image</option></select></label></div><div className="mt-4 overflow-hidden rounded-lg border border-gray-700 bg-[#0b0e14]">{image && <img src={image} alt="Social preview" className="h-36 w-full object-cover" />}<div className="p-3"><p className="font-semibold text-white">{settings.openGraphTitle || settings.seoTitle}</p><p className="text-sm text-gray-400">{settings.openGraphDescription || settings.metaDescription}</p></div></div></Card>
    <Card title="Favicons & Default Images"><div className="grid gap-4 md:grid-cols-2"><Field label="Favicon URL" value={settings.faviconUrl} onChange={v => update('faviconUrl', v)} type="url" /><Field label="Apple Touch Icon" value={settings.appleTouchIcon} onChange={v => update('appleTouchIcon', v)} type="url" /><Field label="Business Logo URL" value={settings.businessLogo} onChange={v => update('businessLogo', v)} type="url" /><Field label="Homepage Share Image" value={settings.homepageShareImage} onChange={v => update('homepageShareImage', v)} type="url" /><Field label="Fallback Open Graph Image" value={settings.fallbackOpenGraphImage} onChange={v => update('fallbackOpenGraphImage', v)} type="url" /><Field label="Fallback Twitter Image" value={settings.fallbackTwitterImage} onChange={v => update('fallbackTwitterImage', v)} type="url" /></div></Card>
    <Card title="Structured Data"><div className="grid gap-3 md:grid-cols-2"><Toggle label="Enable Organization Schema" value={settings.enableOrganizationSchema} onChange={v => update('enableOrganizationSchema', v)} /><Toggle label="Enable Website Schema" value={settings.enableWebsiteSchema} onChange={v => update('enableWebsiteSchema', v)} /><Toggle label="Enable SearchAction Schema (only enable for a real public search page)" value={settings.enableSearchActionSchema} onChange={v => update('enableSearchActionSchema', v)} /><Field label="Organization Name" value={settings.organizationName} onChange={v => update('organizationName', v)} /><Field label="Organization Description" value={settings.organizationDescription} onChange={v => update('organizationDescription', v)} multiline /><Field label="Website URL" value={settings.businessUrl} onChange={v => update('businessUrl', v)} type="url" /><Field label="Business Email" value={settings.businessEmail} onChange={v => update('businessEmail', v)} type="email" /><Field label="Logo URL" value={settings.schemaLogo} onChange={v => update('schemaLogo', v)} type="url" /></div><div className="mt-4"><span className="text-xs font-bold uppercase text-gray-500">Social Profile URLs</span>{settings.socialProfiles.map((url, i) => <div key={i} className="mt-2 flex gap-2"><input value={url} onChange={e => update('socialProfiles', settings.socialProfiles.map((x, n) => n === i ? e.target.value : x))} className="w-full rounded-lg border border-gray-700 bg-[#0b0e14] p-2 text-sm text-white" /><button onClick={() => update('socialProfiles', settings.socialProfiles.filter((_, n) => n !== i))} className="text-red-300"><Trash2 className="h-4 w-4" /></button></div>)}<button onClick={() => update('socialProfiles', [...settings.socialProfiles, ''])} className="mt-2 inline-flex items-center gap-1 text-sm text-cyan-300"><Plus className="h-4 w-4" /> Add profile</button></div></Card>
    <Card title="Search Engine Verification"><div className="grid gap-4 md:grid-cols-2">{([['Google Search Console Verification', 'googleVerification'], ['Bing Webmaster Verification', 'bingVerification'], ['Pinterest Verification', 'pinterestVerification'], ['Yandex Verification', 'yandexVerification']] as const).map(([label, key]) => <Field key={key} label={label} value={settings[key]} onChange={v => update(key, v)} />)}</div></Card>
    <Card title="Advanced"><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-bold uppercase text-gray-500">Robots Meta<select value={settings.robotsMeta} onChange={e => update('robotsMeta', e.target.value as SeoSettings['robotsMeta'])} className="mt-1 block w-full rounded-lg border border-gray-700 bg-[#0b0e14] p-2 text-sm normal-case text-white">{['index,follow','index,nofollow','noindex,follow','noindex,nofollow'].map(x => <option key={x}>{x}</option>)}</select></label><Field label="Sitemap URL" value={settings.sitemapUrl} onChange={v => update('sitemapUrl', v)} type="url" /><div className="md:col-span-2"><Field label="Additional Head Code" value={settings.additionalHeadMarkup} onChange={v => update('additionalHeadMarkup', v)} multiline hint="Scripts are blocked. Review this carefully before saving." /></div></div></Card>
    <div className="sticky bottom-3 flex justify-end"><button onClick={() => void save()} className="inline-flex items-center gap-2 rounded-lg bg-cyan-500 px-5 py-3 font-bold text-slate-950 shadow-lg hover:bg-cyan-400"><Save className="h-4 w-4" /> Save Changes</button></div>
  </div>;
};
