import React, { useState } from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react';
import type { ParcelCalculationFailure, ParcelCalculationResult, ShippingPackage, ShippingProfile } from '../../types';
import { authedFetch } from '../../utils/authedFetch';

const blank = (): Partial<ShippingPackage> => ({ name: '', description: '', lengthIn: 0, widthIn: 0, heightIn: 0, emptyWeightOz: 0, priority: 10, active: true, capacityByProfileId: {} });
const fields: Array<[keyof ShippingPackage, string]> = [['lengthIn','Length (in)'],['widthIn','Width (in)'],['heightIn','Height (in)'],['emptyWeightOz','Empty weight (oz)'],['maxWeightOz','Maximum total weight (oz, optional)'],['priority','Priority / size order']];
export const ShippingPackagesAdminSection: React.FC<{ packages: ShippingPackage[]; profiles: ShippingProfile[]; onRefresh: () => Promise<void> }> = ({ packages, profiles, onRefresh }) => {
  const [draft, setDraft] = useState<Partial<ShippingPackage> | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [counts, setCounts] = useState<Record<string, number>>({}); const [preview, setPreview] = useState<ParcelCalculationResult | ParcelCalculationFailure | null>(null);
  const set = (key: keyof ShippingPackage, value: unknown) => setDraft((current) => ({ ...current, [key]: value }));
  const refresh = async () => { await onRefresh(); setDraft(null); };
  const save = async () => { if (!draft) return; setSaving(true); setError(''); try { await authedFetch('/api/admin/shipping-packages', { method: 'PUT', body: JSON.stringify({ id: draft.id, package: draft }) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save package.'); } finally { setSaving(false); } };
  const seed = async () => { setSaving(true); try { await authedFetch('/api/admin/shipping-packages', { method: 'POST', body: JSON.stringify({ action: 'seed' }) }); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to initialize packages.'); } finally { setSaving(false); } };
  const remove = async (pkg: ShippingPackage) => { if (!window.confirm(`Delete “${pkg.name}”? Deactivate packages that may have historical use.`)) return; try { await authedFetch(`/api/admin/shipping-packages?id=${encodeURIComponent(pkg.id)}`, { method: 'DELETE' }); await onRefresh(); } catch { setError('This package may be in use. Deactivate it instead.'); } };
  const calculate = async () => { try { const payload = await authedFetch<{ result: ParcelCalculationResult | ParcelCalculationFailure }>('/api/admin/shipping-packages', { method: 'POST', body: JSON.stringify({ action: 'preview', profileCounts: counts }) }); setPreview(payload.result); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to calculate preview.'); } };
  return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-xl border border-gray-800 bg-[#131720] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-white">Shipping Packages</h2><p className="mt-1 text-sm text-gray-400">Package dimensions, empty weights, and profile capacity limits.</p></div><button onClick={() => setDraft(blank())} className="flex min-h-11 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4" />Add Shipping Package</button></div>
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{packages.length === 0 && <div className="rounded-xl border border-dashed border-gray-700 p-7 text-center text-gray-300">No packages configured.<br /><button disabled={saving || profiles.length === 0} onClick={seed} className="mt-3 min-h-11 rounded-lg bg-white px-4 font-black text-gray-950">Initialize recommended defaults</button></div>}
    <div className="grid gap-3 md:grid-cols-2">{packages.map((pkg) => <article key={pkg.id} className="rounded-xl border border-gray-800 bg-[#131720] p-4"><div className="flex justify-between gap-3"><div><h3 className="font-black text-white">{pkg.name}</h3><p className="text-sm text-gray-400">{pkg.lengthIn} × {pkg.widthIn} × {pkg.heightIn} in</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-black uppercase ${pkg.active ? 'bg-emerald-500/15 text-emerald-300' : 'bg-gray-700 text-gray-300'}`}>{pkg.active ? 'Active' : 'Inactive'}</span></div><p className="mt-3 text-xs text-gray-500">{pkg.emptyWeightOz} oz packaging • Priority {pkg.priority}{pkg.maxWeightOz != null && ` • ${pkg.maxWeightOz} oz max`}</p><div className="mt-3 flex flex-wrap gap-1">{profiles.map((profile) => <span key={profile.id} className="rounded bg-black/30 px-2 py-1 text-[10px] text-gray-400">{profile.name}: {pkg.capacityByProfileId?.[profile.id] ?? 0}</span>)}</div><div className="mt-4 flex gap-2"><button onClick={() => setDraft({ ...pkg, capacityByProfileId: { ...pkg.capacityByProfileId } })} className="flex min-h-10 flex-1 items-center justify-center gap-2 rounded-lg border border-gray-700 text-sm font-bold text-gray-200"><Edit2 className="h-4 w-4" />Edit</button><button onClick={() => void remove(pkg)} className="min-h-10 rounded-lg border border-red-500/30 px-3 text-red-300"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>
    <section className="rounded-xl border border-gray-800 bg-[#131720] p-4"><h3 className="font-black text-white">Package Calculator Test</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{profiles.filter((profile) => profile.active).map((profile) => <label key={profile.id} className="text-xs font-bold text-gray-400">{profile.name}<input type="number" min="0" step="1" value={counts[profile.id] ?? 0} onChange={(e) => setCounts({ ...counts, [profile.id]: Math.max(0, Number(e.target.value) || 0) })} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label>)}</div><button onClick={() => void calculate()} className="mt-4 min-h-11 w-full rounded-lg bg-blue-600 px-4 font-black text-white sm:w-auto">Calculate Package</button>{preview && <div className="mt-4 rounded-lg bg-black/25 p-4 text-sm text-gray-300">{preview.status === 'ready' ? <><strong className="text-white">{preview.packageName}</strong><p>{preview.lengthIn} × {preview.widthIn} × {preview.heightIn} in</p><p>Items: {preview.itemWeightOz} oz • Packaging: {preview.packagingWeightOz} oz • Final: {preview.totalWeightOz} oz</p></> : <strong className="text-amber-300">{preview.reason}</strong>}</div>}</section>
    {draft && <div className="fixed inset-0 z-[400] flex items-end justify-center bg-black/80 sm:items-center sm:p-4"><div className="max-h-[92dvh] w-full max-w-xl overflow-y-auto rounded-t-2xl border border-gray-700 bg-[#171b24] p-5 sm:rounded-2xl"><h3 className="text-lg font-black text-white">{draft.id ? 'Edit' : 'Add'} Shipping Package</h3><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-400 sm:col-span-2">Package Name<input maxLength={100} value={draft.name ?? ''} onChange={(e) => set('name', e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label><label className="text-xs font-bold text-gray-400 sm:col-span-2">Description<textarea maxLength={500} value={draft.description ?? ''} onChange={(e) => set('description', e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-gray-700 bg-[#0b0e14] p-3 text-white" /></label>{fields.map(([key,label]) => <label key={key} className="text-xs font-bold text-gray-400">{label}<input type="number" min="0" step={key === 'priority' ? 1 : 0.1} value={(draft[key] as number | undefined) ?? ''} onChange={(e) => set(key, e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label>)}<fieldset className="sm:col-span-2"><legend className="text-xs font-black uppercase text-gray-400">Profile Capacity</legend><p className="mb-2 text-[11px] text-gray-500">Blank and 0 both mean this package cannot carry that profile.</p><div className="grid grid-cols-2 gap-2">{profiles.map((profile) => <label key={profile.id} className="text-xs text-gray-400">{profile.name}<input type="number" min="0" step="1" value={draft.capacityByProfileId?.[profile.id] ?? ''} onChange={(e) => set('capacityByProfileId', { ...draft.capacityByProfileId, [profile.id]: e.target.value })} className="mt-1 min-h-11 w-full rounded border border-gray-700 bg-[#0b0e14] px-2 text-white" /></label>)}</div></fieldset><label className="flex min-h-11 items-center gap-3 text-sm font-bold text-gray-200 sm:col-span-2"><input type="checkbox" checked={draft.active !== false} onChange={(e) => set('active', e.target.checked)} className="h-5 w-5" />Active</label></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setDraft(null)} className="min-h-11 rounded-lg border border-gray-700 font-bold text-gray-300">Cancel</button><button disabled={saving || !draft.name?.trim()} onClick={() => void save()} className="min-h-11 rounded-lg bg-blue-600 font-black text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save Package'}</button></div></div></div>}
  </div>;
};
