import React, { useState } from 'react';
import { Edit2, Plus, Trash2 } from 'lucide-react';
import type { ShippingProfile } from '../../types';
import { authedFetch } from '../../utils/authedFetch';

const blank = (): Partial<ShippingProfile> => ({ name: '', description: '', defaultWeightOz: 0, packageType: '', active: true });
export const ShippingProfilesAdminSection: React.FC<{ profiles: ShippingProfile[]; onRefresh: () => Promise<void> }> = ({ profiles, onRefresh }) => {
  const [draft, setDraft] = useState<Partial<ShippingProfile> | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const set = (key: keyof ShippingProfile, value: unknown) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!draft) return; setSaving(true); setError(''); try { await authedFetch('/api/admin/shipping-profiles', { method: 'PUT', body: JSON.stringify({ id: draft.id, profile: draft }) }); setDraft(null); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save profile.'); } finally { setSaving(false); } };
  const remove = async (profile: ShippingProfile) => { if (profile.usageCount) { setError(`This shipping profile is assigned to ${profile.usageCount} items. Deactivate it or reassign those items before deleting.`); return; } if (!window.confirm(`Delete “${profile.name}”?`)) return; try { await authedFetch(`/api/admin/shipping-profiles?id=${encodeURIComponent(profile.id)}`, { method: 'DELETE' }); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete profile.'); } };
  const seed = async () => { setSaving(true); setError(''); try { await authedFetch('/api/admin/shipping-profiles', { method: 'POST', body: JSON.stringify({ action: 'seed' }) }); await onRefresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to initialize profiles.'); } finally { setSaving(false); } };
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 rounded-xl border border-gray-800 bg-[#131720] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-white">Shipping Profiles</h2><p className="mt-1 text-sm text-gray-400">Reusable item weights and package dimensions for future shipping calculations.</p></div><button onClick={() => setDraft(blank())} className="flex min-h-11 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4" />Add Shipping Profile</button></div>
    {error && <div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}
    {profiles.length === 0 && <div className="rounded-xl border border-dashed border-gray-700 p-8 text-center"><p className="text-gray-300">No shipping profiles configured.</p><button disabled={saving} onClick={seed} className="mt-3 min-h-11 rounded-lg bg-white px-4 text-sm font-black text-gray-950">Initialize recommended defaults</button></div>}
    <div className="grid gap-3 md:grid-cols-2">{profiles.map((profile) => <article key={profile.id} className="rounded-xl border border-gray-800 bg-[#131720] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-white">{profile.name}</h3><p className="mt-1 text-xs text-gray-500">{profile.defaultWeightOz} oz{profile.defaultLengthIn != null && ` • ${profile.defaultLengthIn}×${profile.defaultWidthIn ?? '—'}×${profile.defaultHeightIn ?? '—'} in`}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${profile.active ? 'bg-emerald-500/15 text-emerald-300' : 'bg-gray-700 text-gray-300'}`}>{profile.active ? 'Active' : 'Inactive'}</span></div><p className="mt-3 text-sm text-gray-400">{profile.description || 'No description'}</p><p className="mt-2 text-xs text-gray-500">Package: {profile.packageType || 'Not specified'} • Used by {profile.usageCount ?? 0} items</p><div className="mt-4 flex gap-2"><button onClick={() => { setError(''); setDraft({ ...profile }); }} className="flex min-h-10 flex-1 items-center justify-center gap-2 rounded-lg border border-gray-700 text-sm font-bold text-gray-200"><Edit2 className="h-4 w-4" />Edit</button><button onClick={() => void remove(profile)} className="flex min-h-10 items-center justify-center rounded-lg border border-red-500/30 px-3 text-red-300" aria-label={`Delete ${profile.name}`}><Trash2 className="h-4 w-4" /></button></div></article>)}</div>
    {draft && <div className="fixed inset-0 z-[400] flex items-end justify-center bg-black/80 sm:items-center sm:p-4"><div className="max-h-[92dvh] w-full max-w-xl overflow-y-auto rounded-t-2xl border border-gray-700 bg-[#171b24] p-5 sm:rounded-2xl"><h3 className="text-lg font-black text-white">{draft.id ? 'Edit' : 'Add'} Shipping Profile</h3><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-gray-400 sm:col-span-2">Profile Name<input maxLength={100} value={draft.name ?? ''} onChange={(e) => set('name', e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label><label className="text-xs font-bold text-gray-400 sm:col-span-2">Description<textarea maxLength={500} value={draft.description ?? ''} onChange={(e) => set('description', e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-gray-700 bg-[#0b0e14] p-3 text-white" /></label>{[['defaultWeightOz','Weight (oz)'],['defaultLengthIn','Length (in)'],['defaultWidthIn','Width (in)'],['defaultHeightIn','Height (in)']].map(([key,label]) => <label key={key} className="text-xs font-bold text-gray-400">{label}<input type="number" min="0" step="0.1" value={(draft as any)[key] ?? ''} onChange={(e) => set(key as keyof ShippingProfile, e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label>)}<label className="text-xs font-bold text-gray-400 sm:col-span-2">Package Type / Internal Label<input maxLength={80} value={draft.packageType ?? ''} onChange={(e) => set('packageType', e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-white" /></label><label className="flex min-h-11 items-center gap-3 text-sm font-bold text-gray-200 sm:col-span-2"><input type="checkbox" checked={draft.active !== false} onChange={(e) => set('active', e.target.checked)} className="h-5 w-5" />Active</label></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setDraft(null)} className="min-h-11 rounded-lg border border-gray-700 font-bold text-gray-300">Cancel</button><button disabled={saving || !draft.name?.trim()} onClick={() => void save()} className="min-h-11 rounded-lg bg-blue-600 font-black text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save Profile'}</button></div></div></div>}
  </div>;
};
