import React, { useEffect, useState } from 'react';
import type { ShippingOriginSettings } from '../../types';
import { authedFetch } from '../../utils/authedFetch';

const empty: ShippingOriginSettings = { shipFromName: '', shipFromStreet1: '', shipFromStreet2: '', shipFromCity: '', shipFromState: '', shipFromPostalCode: '', shipFromCountry: 'US', shipFromPhone: '' };
export const ShippingOriginAdminSection: React.FC = () => {
  const [origin, setOrigin] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { void authedFetch<{ origin: ShippingOriginSettings }>('/api/admin/shipping-origin').then((data) => setOrigin(data.origin)).catch(() => setMessage('Unable to load the shipping origin.')).finally(() => setLoading(false)); }, []);
  const field = (key: keyof ShippingOriginSettings, label: string, options: React.InputHTMLAttributes<HTMLInputElement> = {}) => <label className="text-xs font-bold text-gray-400">{label}<input {...options} value={origin[key] ?? ''} onChange={(event) => setOrigin({ ...origin, [key]: event.target.value })} className="mt-1 min-h-11 w-full rounded-lg border border-gray-700 bg-[#0b0e14] px-3 text-sm text-white" /></label>;
  const save = async () => { setSaving(true); setMessage(''); try { const data = await authedFetch<{ origin: ShippingOriginSettings }>('/api/admin/shipping-origin', { method: 'PUT', body: JSON.stringify({ origin }) }); setOrigin(data.origin); setMessage('Shipping origin saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save the shipping origin.'); } finally { setSaving(false); } };
  return <section className="rounded-xl border border-gray-800 bg-[#131720] p-4 sm:p-6"><div className="max-w-2xl"><h2 className="text-lg font-black text-white">Ship-from Address</h2><p className="mt-1 text-sm text-gray-400">Used server-side for live carrier quotes. Customers cannot view or change this setting.</p>{loading ? <p className="mt-5 text-sm text-gray-400">Loading shipping origin…</p> : <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="sm:col-span-2">{field('shipFromName','Name',{autoComplete:'organization',maxLength:120})}</div><div className="sm:col-span-2">{field('shipFromStreet1','Address Line 1',{autoComplete:'address-line1',maxLength:160})}</div><div className="sm:col-span-2">{field('shipFromStreet2','Address Line 2 (optional)',{autoComplete:'address-line2',maxLength:160})}</div>{field('shipFromCity','City',{autoComplete:'address-level2',maxLength:100})}{field('shipFromState','State / Region',{autoComplete:'address-level1',maxLength:100})}{field('shipFromPostalCode','Postal Code',{autoComplete:'postal-code',maxLength:32})}{field('shipFromCountry','Country Code',{autoComplete:'country',maxLength:2})}<div className="sm:col-span-2">{field('shipFromPhone','Phone (optional)',{type:'tel',autoComplete:'tel',maxLength:32})}</div><button type="button" disabled={saving} onClick={() => void save()} className="min-h-11 w-full rounded-lg bg-blue-600 px-4 font-black text-white disabled:opacity-50 sm:col-span-2 sm:w-auto">{saving ? 'Saving…' : 'Save Ship-from Address'}</button></div>}{message && <p className="mt-4 rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-gray-200" role="status">{message}</p>}</div></section>;
};
