import { InventoryItem, Item, UpgraderSettings } from './upgraderTypes';

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 'inv-1', name: 'Desert Eagle | Blaze', imageUrl: 'https://picsum.photos/seed/deagle/200/200', coinValue: 450, rarity: 'Legendary', category: 'Pistol' },
  { id: 'inv-2', name: 'AK-47 | Redline', imageUrl: 'https://picsum.photos/seed/ak47/200/200', coinValue: 85, rarity: 'Rare', category: 'Rifle' },
  { id: 'inv-3', name: 'AWP | Dragon Lore', imageUrl: 'https://picsum.photos/seed/awp/200/200', coinValue: 12000, rarity: 'Mythic', category: 'Sniper', locked: true },
  { id: 'inv-4', name: 'Glock-18 | Fade', imageUrl: 'https://picsum.photos/seed/glock/200/200', coinValue: 1200, rarity: 'Epic', category: 'Pistol' },
  { id: 'inv-5', name: 'M4A4 | Howl', imageUrl: 'https://picsum.photos/seed/m4a4/200/200', coinValue: 8500, rarity: 'Mythic', category: 'Rifle' },
  { id: 'inv-6', name: 'USP-S | Kill Confirmed', imageUrl: 'https://picsum.photos/seed/usps/200/200', coinValue: 150, rarity: 'Epic', category: 'Pistol' },
  { id: 'inv-7', name: 'Knife | Karambit Doppler', imageUrl: 'https://picsum.photos/seed/karambit/200/200', coinValue: 1800, rarity: 'Legendary', category: 'Knife' },
  { id: 'inv-8', name: 'P250 | Sand Dune', imageUrl: 'https://picsum.photos/seed/p250/200/200', coinValue: 0.05, rarity: 'Common', category: 'Pistol' },
  { id: 'inv-9', name: 'StatTrak AK-47 | Vulcan', imageUrl: 'https://picsum.photos/seed/vulcan/200/200', coinValue: 950, rarity: 'Epic', category: 'Rifle' },
  { id: 'inv-10', name: 'M9 Bayonet | Marble Fade', imageUrl: 'https://picsum.photos/seed/m9/200/200', coinValue: 1400, rarity: 'Legendary', category: 'Knife', shipping: true },
  { id: 'inv-11', name: 'Butterfly Knife | Lore', imageUrl: 'https://picsum.photos/seed/butterfly/200/200', coinValue: 2200, rarity: 'Mythic', category: 'Knife' },
  { id: 'inv-12', name: 'AWP | Asiimov', imageUrl: 'https://picsum.photos/seed/asiimov/200/200', coinValue: 180, rarity: 'Epic', category: 'Sniper' },
];

export const MOCK_TARGETS: Item[] = [
  { id: 'tar-1', name: 'AWP | Dragon Lore', imageUrl: 'https://picsum.photos/seed/awp/200/200', coinValue: 12500, rarity: 'Mythic', category: 'Sniper', enabled: true },
  { id: 'tar-2', name: 'M4A4 | Howl', imageUrl: 'https://picsum.photos/seed/m4a4/200/200', coinValue: 8800, rarity: 'Mythic', category: 'Rifle', enabled: true },
  { id: 'tar-3', name: 'Karambit | Sapphire', imageUrl: 'https://picsum.photos/seed/sapphire/200/200', coinValue: 15000, rarity: 'Mythic', category: 'Knife', enabled: true },
  { id: 'tar-4', name: 'AK-47 | Fire Serpent', imageUrl: 'https://picsum.photos/seed/fire/200/200', coinValue: 2500, rarity: 'Legendary', category: 'Rifle', enabled: true },
  { id: 'tar-5', name: 'Butterfly Knife | Fade', imageUrl: 'https://picsum.photos/seed/fade/200/200', coinValue: 3200, rarity: 'Legendary', category: 'Knife', enabled: true },
  { id: 'tar-6', name: 'Glock-18 | Fade', imageUrl: 'https://picsum.photos/seed/glock/200/200', coinValue: 1300, rarity: 'Epic', category: 'Pistol', enabled: true },
  { id: 'tar-7', name: 'Desert Eagle | Blaze', imageUrl: 'https://picsum.photos/seed/deagle/200/200', coinValue: 480, rarity: 'Legendary', category: 'Pistol', enabled: true },
  { id: 'tar-8', name: 'USP-S | Kill Confirmed', imageUrl: 'https://picsum.photos/seed/usps/200/200', coinValue: 160, rarity: 'Epic', category: 'Pistol', enabled: true },
  { id: 'tar-9', name: 'AWP | Asiimov', imageUrl: 'https://picsum.photos/seed/asiimov/200/200', coinValue: 195, rarity: 'Epic', category: 'Sniper', enabled: true },
  { id: 'tar-10', name: 'AK-47 | Redline', imageUrl: 'https://picsum.photos/seed/ak47/200/200', coinValue: 95, rarity: 'Rare', category: 'Rifle', enabled: true },
  { id: 'tar-11', name: 'M4A1-S | Printstream', imageUrl: 'https://picsum.photos/seed/print/200/200', coinValue: 450, rarity: 'Epic', category: 'Rifle', enabled: true },
  { id: 'tar-12', name: 'AWP | Graphite', imageUrl: 'https://picsum.photos/seed/graphite/200/200', coinValue: 220, rarity: 'Rare', category: 'Sniper', enabled: true },
  { id: 'tar-13', name: 'StatTrak AK-47 | Vulcan', imageUrl: 'https://picsum.photos/seed/vulcan/200/200', coinValue: 1050, rarity: 'Epic', category: 'Rifle', enabled: true },
  { id: 'tar-14', name: 'Flip Knife | Doppler', imageUrl: 'https://picsum.photos/seed/flip/200/200', coinValue: 650, rarity: 'Rare', category: 'Knife', enabled: true },
  { id: 'tar-15', name: 'Bayonet | Tiger Tooth', imageUrl: 'https://picsum.photos/seed/bayonet/200/200', coinValue: 850, rarity: 'Legendary', category: 'Knife', enabled: true },
  { id: 'tar-16', name: 'P250 | Sand Dune', imageUrl: 'https://picsum.photos/seed/p250/200/200', coinValue: 0.10, rarity: 'Common', category: 'Pistol', enabled: true },
  { id: 'tar-17', name: 'Five-SeveN | Hyper Beast', imageUrl: 'https://picsum.photos/seed/hyper/200/200', coinValue: 45, rarity: 'Rare', category: 'Pistol', enabled: true },
  { id: 'tar-18', name: 'MAC-10 | Neon Rider', imageUrl: 'https://picsum.photos/seed/neon/200/200', coinValue: 25, rarity: 'Rare', category: 'SMG', enabled: true },
  { id: 'tar-19', name: 'MP9 | Food Chain', imageUrl: 'https://picsum.photos/seed/food/200/200', coinValue: 15, rarity: 'Uncommon', category: 'SMG', enabled: true },
  { id: 'tar-20', name: 'Galil AR | Eco', imageUrl: 'https://picsum.photos/seed/eco/200/200', coinValue: 8, rarity: 'Uncommon', category: 'Rifle', enabled: true },
  { id: 'tar-21', name: 'FAMAS | Mecha Industries', imageUrl: 'https://picsum.photos/seed/mecha/200/200', coinValue: 12, rarity: 'Uncommon', category: 'Rifle', enabled: true },
  { id: 'tar-22', name: 'SG 553 | Integrale', imageUrl: 'https://picsum.photos/seed/integ/200/200', coinValue: 350, rarity: 'Epic', category: 'Rifle', enabled: true },
  { id: 'tar-23', name: 'AUG | Akihabara Accept', imageUrl: 'https://picsum.photos/seed/aug/200/200', coinValue: 4500, rarity: 'Mythic', category: 'Rifle', enabled: true },
  { id: 'tar-24', name: 'SSG 08 | Blood in the Water', imageUrl: 'https://picsum.photos/seed/ssg/200/200', coinValue: 120, rarity: 'Rare', category: 'Sniper', enabled: true },
  { id: 'tar-25', name: 'SCAR-20 | Cyrex', imageUrl: 'https://picsum.photos/seed/scar/200/200', coinValue: 10, rarity: 'Uncommon', category: 'Sniper', enabled: true },
  { id: 'tar-26', name: 'G3SG1 | The Executioner', imageUrl: 'https://picsum.photos/seed/g3/200/200', coinValue: 15, rarity: 'Uncommon', category: 'Sniper', enabled: true },
  { id: 'tar-27', name: 'Nova | Hyper Beast', imageUrl: 'https://picsum.photos/seed/nova/200/200', coinValue: 20, rarity: 'Rare', category: 'Shotgun', enabled: true },
  { id: 'tar-28', name: 'XM1014 | Tranquility', imageUrl: 'https://picsum.photos/seed/xm/200/200', coinValue: 18, rarity: 'Rare', category: 'Shotgun', enabled: true },
  { id: 'tar-29', name: 'Sawed-Off | The Kraken', imageUrl: 'https://picsum.photos/seed/sawed/200/200', coinValue: 22, rarity: 'Rare', category: 'Shotgun', enabled: true },
  { id: 'tar-30', name: 'MAG-7 | Justice', imageUrl: 'https://picsum.photos/seed/mag/200/200', coinValue: 14, rarity: 'Rare', category: 'Shotgun', enabled: true },
];

export const DEFAULT_SETTINGS: UpgraderSettings = {
  enabled: true,
  edgeMultiplier: 0.95,
  minChance: 0.01,
  maxChance: 80,
  minUpgradeRatio: 1.1,
  maxTargetValueRatio: 100,
  cooldownMs: 5000,
  allowFromFreeBox: true,
  allowFromPromo: true,
};
